# Generated by Django 4.2.4 on 2023-11-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=20, verbose_name='Название пиццы')),
                ('pizza_img', models.TextField(verbose_name='Картинка')),
                ('pizza_price', models.CharField(max_length=10, verbose_name='Цена')),
                ('pizza_weight', models.TextField(verbose_name='Вес')),
                ('pizza_description', models.TextField(verbose_name='Состав')),
            ],
            options={
                'verbose_name': 'Пицца',
                'verbose_name_plural': 'Пиццы',
                'ordering': ['-id'],
            },
        ),
    ]
